version: 0.2

env:
  variables:
    TF_COMMAND: "apply"
    # TF_COMMAND: "destroy"

phases:
  pre_build:
    commands:
      - sed -i 's/# backend/backend/g' h1-versions.tf
      - sed -i 's/profile =/# profile =/g' h1-versions.tf
      - terraform init -backend-config=config-dev.conf
      - terraform validate
      - terraform plan -lock=false -var-file=h0-dev.tfvars
  build:
    commands:
      - terraform "$TF_COMMAND" -var-file=h0-dev.tfvars -auto-approve